// Generates web/players/openingBook.js — run with:
//   node web/players/generateOpeningBook.js
//
// The runtime "Perfect AI" caps its minimax at MAX_DEPTH plies so a browser tab
// can't hang on pathological rules. For the DEFAULT rules the game can run ~40
// moves deep, so from the opening the capped search bottoms out and can't play
// perfectly. This script solves the game exactly (uncapped alpha-beta — cheap
// for the default rules, which have a forced result that prunes hard) and writes
// an opening book: the game-theoretically optimal move for every reachable
// position in the first BOOK_DEPTH plies. The runtime replays these for a perfect
// opening, then falls back to the regular depth-capped search.
//
// The whole alive state space is far too large to store, so the book is bounded
// to the opening. We make ONE depth-first alpha-beta pass with pruning DISABLED
// inside the book region (so those node values are exact and the recorded moves
// are provably optimal) and ENABLED below it (so each deep subtree is explored
// once — values are only -1/0/+1, which prunes hard).

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { Game, Result, DEFAULTS } from "../Game.js";
import { MAX_DEPTH } from "./PerfectAiPlayer.js";

// How many opening plies to precompute. Every reachable position of length
// < BOOK_DEPTH gets an entry. Size grows ~2x per ply (see the alive counts the
// script prints); this is the knob that trades book size for a longer perfect
// opening before the depth-capped runtime search takes over.
const BOOK_DEPTH = 14;

const cfg = DEFAULTS;
const bookMove = new Map(); // shallow non-terminal state -> optimal mark for the mover
let nodes = 0;
let deepestAlive = 0;

// One reusable Game to test results without allocating per node.
const probe = new Game(cfg);
function resultOf(state) {
  probe.state = state;
  return probe.result();
}

function terminalValueP1(result) {
  if (result === Result.PLAYER_1_WIN) return 1;
  if (result === Result.PLAYER_2_WIN) return -1;
  return 0; // DRAW
}

// Exact game value of `state` from Player 1's perspective (+1 P1 win / 0 draw /
// -1 P2 win). Player 1 moves on even-length states and maximizes; Player 2 moves
// on odd-length states and minimizes. Inside the book region we pass a full
// (-inf, inf) window to children so every child value is exact and the recorded
// move is provably optimal; below it we prune normally.
function search(state, alpha, beta) {
  nodes++;
  const r = resultOf(state);
  if (r !== Result.NOT_FINISHED) return terminalValueP1(r);
  if (state.length > deepestAlive) deepestAlive = state.length;

  const inBook = state.length < BOOK_DEPTH;
  const player1ToMove = state.length % 2 === 0;
  let best = player1ToMove ? -Infinity : Infinity;
  let bestMark = null;

  for (const mark of ["X", "O"]) {
    const childAlpha = inBook ? -Infinity : alpha;
    const childBeta = inBook ? Infinity : beta;
    const v = search(state + mark, childAlpha, childBeta);
    if (player1ToMove) {
      if (v > best) { best = v; bestMark = mark; }
      if (!inBook) { alpha = Math.max(alpha, best); if (beta <= alpha) break; }
    } else {
      if (v < best) { best = v; bestMark = mark; }
      if (!inBook) { beta = Math.min(beta, best); if (beta <= alpha) break; }
    }
  }

  if (inBook && bestMark !== null) bookMove.set(state, bestMark);
  return best;
}

console.log(`Config: P1 ${cfg.p1Length}x${cfg.p1Repeats}, P2 ${cfg.p2Length}x${cfg.p2Repeats}  |  MAX_DEPTH ${MAX_DEPTH}  |  BOOK_DEPTH ${BOOK_DEPTH}`);
console.log("Solving opening (single alpha-beta pass)...");

const started = process.hrtime.bigint();
const rootValue = search("", -Infinity, Infinity);
const ms = Number(process.hrtime.bigint() - started) / 1e6;

console.log(`Root value (Player 1 perspective): ${rootValue}  (1=P1 win, 0=draw, -1=P2 win)`);
console.log(`Nodes: ${nodes.toLocaleString()}  |  deepest position seen: ${deepestAlive}  |  ${ms.toFixed(0)} ms`);

const entries = [...bookMove.entries()]
  .sort(([a], [b]) => (a.length - b.length) || (a < b ? -1 : a > b ? 1 : 0));
const lines = entries.map(([state, mark]) => `  ${JSON.stringify(state)}: ${JSON.stringify(mark)},`);

const out = `// AUTO-GENERATED by generateOpeningBook.js — do not edit by hand.
// Opening book of game-theoretically optimal moves for the DEFAULT win rules
// (P1: length ${cfg.p1Length} x ${cfg.p1Repeats}, P2: length ${cfg.p2Length} x ${cfg.p2Repeats}). Covers every reachable position in the first
// ${BOOK_DEPTH} plies; the runtime replays these for a perfect opening, then falls back to
// the depth-capped alpha-beta search. Regenerate with:
//   node web/players/generateOpeningBook.js
export const OPENING_BOOK_CONFIG = ${JSON.stringify(cfg)};
export const OPENING_BOOK = {
${lines.join("\n")}
};
`;

const outPath = join(dirname(fileURLToPath(import.meta.url)), "openingBook.js");
writeFileSync(outPath, out);
console.log(`Wrote ${entries.length} book entries -> ${outPath}`);
